variable "name" {
  description = "Prefix for resource names, e.g. pulsewatch"
  type        = string
}

variable "private_db_subnet_ids" {
  description = "Private DB subnets the database can be placed in"
  type        = list(string)
}

variable "rds_sg_id" {
  description = "Security group that controls who can reach the database"
  type        = string
}

variable "db_name" {
  description = "Name of the database created inside the instance (letters, numbers, underscores only)"
  type        = string
}

variable "username" {
  description = "Master username. The password is generated by RDS and stored in Secrets Manager"
  type        = string
}

variable "engine_version" {
  description = "Postgres major version. AWS picks the latest minor version"
  type        = string
  default     = "16"
}

variable "instance_class" {
  description = "Size of the database instance"
  type        = string
  default     = "db.t4g.micro"
}

variable "allocated_storage" {
  description = "Disk size in GB. 20 is the minimum for Postgres"
  type        = number
  default     = 20
}

variable "multi_az" {
  description = "Keep a standby copy in a second AZ. Doubles the cost"
  type        = bool
  default     = false
}